const SECURITIES=Object.freeze([{symbol:'8035.T',code:'8035',name:'東京エレクトロン'},{symbol:'6857.T',code:'6857',name:'アドバンテスト'},{symbol:'5803.T',code:'5803',name:'フジクラ'},{symbol:'5016.T',code:'5016',name:'JX金属'},{symbol:'6920.T',code:'6920',name:'レーザーテック'},{symbol:'9983.T',code:'9983',name:'ファーストリテイリング'},{symbol:'7974.T',code:'7974',name:'任天堂'},{symbol:'285A.T',code:'285A',name:'キオクシアホールディングス'},{symbol:'9984.T',code:'9984',name:'ソフトバンクグループ'},{symbol:'5706.T',code:'5706',name:'三井金属'}]);
const cleanNumber=value=>{if(value===null||value===undefined||String(value).trim()==='')return null;const parsed=Number(String(value).replaceAll(',',''));return Number.isFinite(parsed)?parsed:null};
const decode=text=>text.replaceAll('&nbsp;',' ').replaceAll('&amp;','&').replaceAll('&#x2F;','/').replaceAll('&#47;','/').replaceAll('&minus;','-').replaceAll('−','-');
const stripHtml=html=>decode(html).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const tokyoDate=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const value=type=>parts.find(part=>part.type===type)?.value;return`${value('year')}-${value('month')}-${value('day')}`};
const timeToIso=time=>time?`${tokyoDate()}T${time}:00+09:00`:null;
function parseYahooJapan(html){const text=stripHtml(html);const priceMatch=text.match(/([0-9]{1,3}(?:,[0-9]{3})*(?:\.[0-9]+)?)\s*前日比[\s\S]{0,160}?リアルタイム株価\s*(\d{1,2}:\d{2})/);if(!priceMatch)throw new Error('Yahoo Japan real-time quote pattern was not found');const highMatch=text.match(/高値\s*(?:用語\s*)?([0-9]{1,3}(?:,[0-9]{3})*(?:\.[0-9]+)?)\s*\((\d{1,2}:\d{2})\)/);const lowMatch=text.match(/安値\s*(?:用語\s*)?([0-9]{1,3}(?:,[0-9]{3})*(?:\.[0-9]+)?)\s*\((\d{1,2}:\d{2})\)/);const price=cleanNumber(priceMatch[1]),dayHigh=cleanNumber(highMatch?.[1]),dayLow=cleanNumber(lowMatch?.[1]);return{price,quote_time:timeToIso(priceMatch[2]),day_high:dayHigh,day_low:dayLow,in_day_range:price!==null&&(dayHigh===null||price<=dayHigh)&&(dayLow===null||price>=dayLow),source:'Yahoo!ファイナンス日本版',source_mode:'realtime-labelled'}}
async function fetchYahooJapan(security){const response=await fetch(`https://finance.yahoo.co.jp/quote/${security.symbol}`,{headers:{Accept:'text/html,application/xhtml+xml','Accept-Language':'ja-JP,ja;q=0.9','User-Agent':'Mozilla/5.0 (compatible; ValueScopeDemo/1.2)'}});if(!response.ok)throw new Error(`Yahoo Japan HTTP ${response.status}`);return parseYahooJapan(await response.text())}
async function fetchGoogleFinance(security){const response=await fetch(`https://www.google.com/finance/quote/${security.code}:TYO?hl=ja`,{headers:{Accept:'text/html,application/xhtml+xml','Accept-Language':'ja-JP,ja;q=0.9','User-Agent':'Mozilla/5.0 (compatible; ValueScopeDemo/1.2)'}});if(!response.ok)throw new Error(`Google Finance HTTP ${response.status}`);const html=await response.text();const patterns=[/data-last-price=["']?([0-9.]+)/i,/<[^>]*class=["'][^"']*YMlKec[^"']*["'][^>]*>\s*[¥￥]?\s*([0-9,.]+)/i,/\[\s*"[A-Z]+"\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*,/];let price=null;for(const pattern of patterns){const match=html.match(pattern);price=cleanNumber(match?.[1]);if(price!==null)break}const timestampMatch=html.match(/data-last-normal-market-timestamp=["']?([0-9]+)/i);if(price===null)throw new Error('Google Finance price pattern was not found');return{price,quote_time:timestampMatch?new Date(Number(timestampMatch[1])*1000).toISOString():null,source:'Google Finance',source_mode:'secondary-check'}}
const settled=result=>result.status==='fulfilled'?result.value:null;const errorName=result=>result.status==='rejected'?String(result.reason?.message??result.reason??'unknown error'):null;
async function buildQuote(security){const[yahooResult,googleResult]=await Promise.allSettled([fetchYahooJapan(security),fetchGoogleFinance(security)]);const yahoo=settled(yahooResult),google=settled(googleResult),primary=yahoo??google,secondary=yahoo&&google?google:null;if(!primary?.price)return{...security,current_price:null,usable:false,verification:'unavailable',errors:[errorName(yahooResult),errorName(googleResult)].filter(Boolean)};const difference=secondary?.price?Math.abs(primary.price-secondary.price)/primary.price*100:null,discrepancy=difference!==null&&difference>3,usable=primary.in_day_range!==false&&!discrepancy;let verification='single-source';if(secondary&&difference!==null&&difference<=1)verification='double-checked';else if(secondary&&difference!==null&&difference<=3)verification='checked-with-time-skew';else if(discrepancy)verification='price-discrepancy';return{...security,current_price:primary.price,quote_time:primary.quote_time,primary_source:primary.source,primary_source_mode:primary.source_mode,day_high:yahoo?.day_high??null,day_low:yahoo?.day_low??null,secondary_price:secondary?.price??null,secondary_time:secondary?.quote_time??null,secondary_source:secondary?.source??null,max_difference_pct:difference,verification,usable,errors:[errorName(yahooResult),errorName(googleResult)].filter(Boolean)}}
export async function onRequestGet(context){const requestUrl=new URL(context.request.url),cacheKey=new Request(requestUrl.origin+requestUrl.pathname,{method:'GET'}),cached=await caches.default.match(cacheKey);if(cached)return cached;const quotes=await Promise.all(SECURITIES.map(buildQuote));const response=Response.json({generated_at:new Date().toISOString(),timezone:'Asia/Tokyo',refresh_seconds:60,source_policy:{primary:'Yahoo!ファイナンス日本版のリアルタイム表示',secondary:'Google Finance',fallback:'取得できた一方のソースを使用し、single-sourceと明示',entry_check:'仮想約定時はYahoo日本版・Google Finance・Yahoo分足APIで照合済み',warning:'取引所認定の直接配信ではなく、配信元により遅延・停止・訂正される場合があります。'},quotes},{headers:{'Cache-Control':'public, max-age=20, s-maxage=20, stale-while-revalidate=20','Content-Type':'application/json; charset=utf-8','X-Content-Type-Options':'nosniff'}});context.waitUntil(caches.default.put(cacheKey,response.clone()));return response}
