import{expect,test}from'@playwright/test';
const bars=Array.from({length:80},(_,index)=>{const date=new Date(Date.UTC(2026,3,1+index));const close=10000+index*35+(index%5-2)*40;return{date:date.toISOString().slice(0,10),open:close-25,high:close+90,low:close-110,close,adjusted_close:close,volume:1000000+index*10000,sma20:index>=19?close-250:null,sma60:index>=59?close-600:null}});
const detail={generated_at:'2026-08-08T00:00:00Z',code:'8035',company_name:'東京エレクトロン',security:{code:'8035',company_name:'東京エレクトロン',market:'プライム',sector:'電気機器'},ranking:{code:'8035',company_name:'東京エレクトロン',overall_score:82,value_score:70,quality_score:85},decision:{company_name:'東京エレクトロン',holding:{quantity:100,avg_cost:10000},quote:{valid:true,quote_time:'2026-08-07T15:30:00+09:00',verification:'double-checked'},decision:{action:'SIM_HOLD',confidence:78},fundamental:{value_score:72,quality_score:83,growth_stability_score:68,value_trap_risk:24,data_completeness:92,fcf_yield:.04,roe:.18,operating_margin:.2,positive_reasons:['品質が高い'],risk_reasons:['Freeデータは遅延']},technical:{price:12700,sma20:12450,sma60:11900,rsi14:61,momentum20_pct:5,momentum60_pct:12,volatility20_pct:38,drawdown20_pct:-3,positive_reasons:['上昇トレンド'],risk_reasons:[]}},data_cutoff:'2026-05-11',plan:'free',financial_history_status:'available',financial_capabilities:{summary:true,full_statements:false},financial_summaries:[{disclosed_date:'2026-05-01',period_end:'2026-03-31',document_type:'通期決算短信',net_sales:1200000000,operating_profit:240000000,ordinary_profit:250000000,profit:180000000,eps:180,total_assets:3000000000,equity:1800000000,operating_cash_flow:300000000,investing_cash_flow:-100000000,financing_cash_flow:-50000000},{disclosed_date:'2025-05-01',period_end:'2025-03-31',net_sales:1000000000,operating_profit:180000000,profit:130000000,eps:130}],next_earnings_date:'2026-10-30',official_disclosures:[],official_disclosure_status:'tdnet_addon_not_configured',chart:bars,news:[{title:'東京エレクトロンの最新動向',link:'https://example.com/news',published_at:'2026-08-07T00:00:00Z',source:'Example'}],source_status:{chart:{ok:true},news:{ok:true},financials:{ok:true},disclosures:{ok:false}},paper_only:true};
async function mock(page,slow=0){await page.route('**/api/stock-detail**',async route=>{if(slow)await new Promise(resolve=>setTimeout(resolve,slow));await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(detail)})});await page.route('**/api/quotes**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({generated_at:'2026-08-07T06:30:00Z',portfolio:{total_entry_value:100,total_current_value:100,total_unrealized_pnl:0,total_return_pct:0},positions:[]})}));}
async function openScreen(page,target){const button=page.locator(`#adaptiveMobileNav [data-adaptive-target="${target}"]`);await button.click();}

test('iPhone bottom navigation switches screens and restores history',async({page})=>{await page.setViewportSize({width:390,height:844});await mock(page);await page.goto('/',{waitUntil:'domcontentloaded'});await openScreen(page,'screening');await expect(page.locator('body')).toHaveAttribute('data-phone-screen','screening');await expect(page.locator('#parameterControl')).toBeVisible();await openScreen(page,'performance');await expect(page.locator('#mobilePerformanceSubnav')).toBeVisible();await page.locator('[data-performance-panel="chart"]').click();await expect(page.locator('body')).toHaveAttribute('data-phone-performance-panel','chart');await page.goBack();await expect(page.locator('body')).toHaveAttribute('data-phone-screen','performance');const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,inner:window.innerWidth}));expect(width.scroll).toBeLessThanOrEqual(width.inner+2)});

test('PC double-click opens rich stock detail and tabs',async({page})=>{await page.setViewportSize({width:1440,height:900});await mock(page);await page.goto('/',{waitUntil:'domcontentloaded'});const row=page.locator('#rankingBody tr[data-code="8035"]').first();await expect(row).toBeVisible({timeout:15000});await row.dblclick();await expect(page.locator('#stockDetailSheet')).toBeVisible();await expect(page.getByText('企業価値・財務の理由')).toBeHidden();await page.getByRole('tab',{name:'推奨理由'}).click();await expect(page.getByText('企業価値・財務の理由')).toBeVisible();await expect(page.getByText('売買タイミングの理由')).toBeVisible();await page.getByRole('tab',{name:'決算'}).click();await expect(page.getByText('通期決算短信')).toBeVisible();await page.getByRole('tab',{name:'開示・ニュース'}).click();await expect(page.getByText('TDnet/Company Disclosure add-on未接続')).toBeVisible();await expect(page.getByText('一般ニュース（公式開示ではありません）')).toBeVisible();await page.getByRole('tab',{name:'チャート'}).click();await expect(page.locator('#stockCandlestickChart')).toBeVisible();await expect(page.getByText('SMA20')).toBeVisible();await expect(page.getByText('SMA60')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#stockDetailSheet')).toBeHidden()});

test('iPhone detail button opens full-screen sheet before slow remote data',async({page})=>{await page.setViewportSize({width:375,height:812});await mock(page,2500);await page.goto('/',{waitUntil:'domcontentloaded'});await openScreen(page,'data');const button=page.locator('#rankingBody tr[data-code="8035"] .stock-detail-trigger').first();await expect(button).toBeVisible({timeout:15000});await button.click();await expect(page.locator('#stockDetailSheet')).toBeVisible({timeout:2000});const box=await page.locator('#stockDetailSheet').boundingBox();expect(Math.round(box.width)).toBe(375);expect(Math.round(box.height)).toBe(812);await expect(page.locator('#stockDetailStatus')).toContainText('保存済み分析');await page.locator('#stockDetailBack').click();await expect(page.locator('#stockDetailSheet')).toBeHidden()});
