import{expect,test}from'@playwright/test';
const quotePayload={generated_at:'2026-08-07T06:30:00Z',portfolio:{total_entry_value:100,total_current_value:105,total_unrealized_pnl:5,total_return_pct:5,winners:1,losers:0,unchanged:0,usable_quotes:1,double_checked:1},positions:[{symbol:'8035.T',code:'8035',name:'東京エレクトロン',entry_price:100,current_price:105,unrealized_pnl:5,return_pct:5,verification:'double-checked',usable:true,quote_time:'2026-08-07T15:30:00+09:00'}]};
const candles=Array.from({length:90},(_,index)=>({date:`2026-${String(4+Math.floor(index/28)).padStart(2,'0')}-${String(1+index%28).padStart(2,'0')}`,open:100+index*.4,high:102+index*.4,low:99+index*.4,close:101+index*.4,volume:100000+index*500}));
const securityFixture={schema_version:1,generated_at:'2026-08-08T00:00:00Z',code:'8035',name:'東京エレクトロン',symbol:'8035.T',market:'Prime',sector:'電気機器',rank:1,action:'SIM_HOLD',confidence:72,data_dates:{effective_fundamental_cutoff:'2026-05-11',latest_disclosure_date:'2026-07-31',latest_price_date:'2026-08-07'},fundamental:{score:78,value_score:73,quality_score:82,growth_stability_score:70,value_trap_risk:22,data_completeness:88,earnings_yield:.05,book_to_market:.4,fcf_yield:.03,roe:.21,operating_margin:.18,missing:[]},technical:{price:136,sma20:130,sma60:120,rsi14:61,momentum20_pct:5,momentum60_pct:12,volatility20_pct:35,drawdown20_pct:-3,score:74,regime:'UPTREND'},recommendation:{summary:'保有継続',fundamental_reasons_positive:['割安スコアが高い','ROEが良好'],fundamental_risks:['FreeプランのFundamentalは遅延'],technical_reasons_positive:['株価がSMA20を上回る','SMA20がSMA60を上回る'],technical_risks:['短期変動率に注意'],evidence_dates:{fundamental:'2026-05-11',technical:'2026-08-07'},data_quality:88},financials:{status:'ok',details_status:'ok',periods:[{disclosure_date:'2026-07-31',period_type:'Q1',sales:600000000000,operating_profit:160000000000,net_profit:120000000000,eps:250,changes:{sales_pct:10,operating_profit_pct:12,net_profit_pct:8,eps_pct:9}},{disclosure_date:'2025-07-31',period_type:'Q1',sales:545000000000,operating_profit:142000000000,net_profit:111000000000,eps:229,changes:{}}],latest_details:{TotalAssets:2500000000000,NetAssets:1900000000000,CashFlowsFromOperatingActivities:240000000000},missing:[]},earnings:{status:'ok',next:{scheduled_date:'2026-10-30',quarter:'Q2'},history:[{publication_date:'2026-07-01',scheduled_date:'2026-07-31',quarter:'Q1',fiscal_year_end:'2027-03-31'}]},disclosures:{status:'not_entitled',items:[],requires_addon:true,search_url:'https://www.google.com/search?q=Tokyo+Electron+news'},chart:{status:'ok',source:'fixture',rows:candles},capabilities:{jquants_api_key:'configured',financial_summary:'ok',financial_details:'ok',earnings_dates:'ok',tdnet:'not_entitled'},warnings:['TDnet/Company Disclosure add-on is unavailable; no headlines are fabricated.'],paper_only:true};
const adaptiveFixture={status:'collecting_data',observations:5,required_observations:63,walk_forward_windows:0,required_windows:3,fundamental_locked:true,fundamental_snapshots:1,reporting_periods:1,champion:{name:'balanced',objective:{value:0},metrics:{}},challenger:{name:'low_volatility',policy:{name:'low_volatility',fundamental:{buy_fundamental:58,buy_quality:62,buy_completeness:45,buy_max_trap:40},technical:{buy_technical:55},risk:{stop_loss_pct:-6,max_drawdown_pct:-9}},objective:{value:1.2},metrics:{}},promotion_guardrails:{checks:{enough_oos_sessions:false,enough_windows:false,objective_improvement:true,drawdown_not_worse:true,turnover_within_limit:true,parameter_stability:false,data_quality_ok:true}},parameter_classification:[{group:'fundamental',label:'Fundamental',ownership:'固定中',user_adjustable:true},{group:'technical',label:'Technical',ownership:'AI候補',user_adjustable:true},{group:'risk',label:'Risk',ownership:'AI候補',user_adjustable:true}],objective_formula:'OOS return + downside-adjusted return - drawdown - turnover',warnings:['OOS履歴が不足しています。自動修正は行っていません。']};
async function mock(page){await page.route('**/api/quotes**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(quotePayload)}));await page.route('**/api/portfolio-status**',route=>route.fulfill({status:200,contentType:'text/plain',body:'generated_at\t2026-08-07T06:30:00Z\ntotal\t100\t105\t5\t5\t1\t0\t0\t1\t1\n'}));await page.route('**/api/security-detail**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(securityFixture)}));await page.route('**/data/adaptive-strategy/status.json**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(adaptiveFixture)}));await page.route('**/data/adaptive-strategy/candidates.json**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({candidates:[adaptiveFixture.challenger])}));await page.route('**/data/adaptive-strategy/audit-log.json**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({events:[]})}));}
async function gotoPhone(page,width=390,height=844){await page.setViewportSize({width,height});await mock(page);await page.goto('/',{waitUntil:'domcontentloaded'});await expect(page.locator('#mobileTaskFlow')).toBeVisible({timeout:20000})}
async function primary(page,target){const button=page.locator(`#adaptiveMobileNav [data-adaptive-target="${target}"]`);await expect(button).toBeVisible();await button.click()}
async function task(page,name){const button=page.locator('#mobileTaskFlow [data-mobile-task]').filter({hasText:name});await expect(button).toBeVisible();await button.click()}
async function noOverflow(page){const values=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth:window.innerWidth}));expect(values.scrollWidth).toBeLessThanOrEqual(values.innerWidth+2)}

test('iPhone tasks hide unrelated large modules and browser history restores task',async({page})=>{await gotoPhone(page);await primary(page,'performance');await task(page,'資産推移');await expect(page.locator('#performanceAnalytics')).toBeVisible();await expect(page.locator('#demoTrade')).toBeHidden();await expect(page.locator('#riskDiagnostics')).toBeHidden();await task(page,'原因分析');await expect(page.locator('#riskDiagnostics')).toBeVisible();await expect(page.locator('#performanceAnalytics')).toBeHidden();await page.goBack();await expect(page.locator('#performanceAnalytics')).toBeVisible();await expect(page.locator('body')).toHaveAttribute('data-phone-task','curve');const height=await page.evaluate(()=>document.documentElement.scrollHeight/window.innerHeight);expect(height).toBeLessThan(8);await noOverflow(page)});

test('conditions are navigated by buttons and show parameter classification',async({page})=>{await gotoPhone(page,375,812);await primary(page,'screening');await task(page,'Fundamental');await expect(page.locator('#parameterControl')).toBeVisible();await expect(page.locator('[data-parameter-tab="fundamental"]')).toHaveAttribute('aria-selected','true');await expect(page.locator('.parameter-classification-legend')).toContainText('Fundamental');await task(page,'Technical');await expect(page.locator('[data-parameter-tab="technical"]')).toHaveAttribute('aria-selected','true');await task(page,'Risk');await expect(page.locator('[data-parameter-tab="risk"]')).toHaveAttribute('aria-selected','true');await noOverflow(page)});

test('PC double click opens security detail with five tabs and candlestick tools',async({page})=>{await page.setViewportSize({width:1440,height:900});await mock(page);await page.goto('/',{waitUntil:'domcontentloaded'});const row=page.locator('#rankingBody tr').first();await expect(row).toBeVisible({timeout:20000});await row.dblclick();const dialog=page.locator('#securityDetailDialog');await expect(dialog).toBeVisible();await expect(dialog.locator('[role="tab"]')).toHaveCount(5);await dialog.getByRole('tab',{name:'チャート'}).click();await expect(dialog.locator('.candle').first()).toBeVisible();await expect(dialog.locator('.sma20')).toBeVisible();await expect(dialog.locator('.sma60')).toBeVisible();await dialog.getByRole('button',{name:'3M'}).click();await expect(dialog.locator('[data-chart-period="3m"]')).toHaveAttribute('aria-pressed','true');await dialog.getByRole('tab',{name:'推奨理由'}).click();await expect(dialog).toContainText('Fundamentalの推奨理由');await expect(dialog).toContainText('Technicalの推奨理由');await dialog.getByRole('tab',{name:'決算'}).click();await expect(dialog).toContainText('決算サマリー');await expect(dialog).toContainText('決算発表予定');await dialog.getByRole('tab',{name:'ニュース・開示'}).click();await expect(dialog).toContainText('適時開示データは未接続');await expect(dialog).toContainText('架空ニュースは表示しません')});

test('iPhone explicit detail button opens a full-screen sheet and switches all tabs',async({page})=>{await gotoPhone(page);await primary(page,'decision');await task(page,'ランキング');const button=page.locator('#rankingBody .security-detail-button').first();await expect(button).toBeVisible({timeout:20000});await button.click();const dialog=page.locator('#securityDetailDialog');await expect(dialog).toBeVisible();const box=await dialog.locator('.security-detail-sheet').boundingBox();expect(box.width).toBeGreaterThanOrEqual(388);expect(box.height).toBeGreaterThanOrEqual(840);for(const name of['概要','決算','ニュース・開示','チャート','推奨理由']){await dialog.getByRole('tab',{name}).click();await expect(dialog.getByRole('tab',{name})).toHaveAttribute('aria-selected','true')}await expect(dialog.getByRole('button',{name:'銘柄詳細を閉じる'})).toBeFocused();await page.keyboard.press('Escape');await expect(dialog).toBeHidden();await noOverflow(page)});

test('AI learning task is honest about insufficient history and local-only application',async({page})=>{await gotoPhone(page);await primary(page,'data');await task(page,'AI学習');const section=page.locator('#adaptiveLearning');await expect(section).toBeVisible();await expect(section).toContainText('学習データ収集中');await expect(section).toContainText('Fundamentalは固定中');await expect(section).toContainText('5 / 63営業日');await expect(section).toContainText('自動修正は行っていません');await section.getByRole('button',{name:'AI提案をブラウザ条件へ反映'}).click();await expect(section).toContainText('日次デモ戦略は変更していません')});

test('security dialog accessibility smoke',async({page})=>{await page.setViewportSize({width:1440,height:900});await mock(page);await page.goto('/',{waitUntil:'domcontentloaded'});await page.locator('#rankingBody tr').first().dblclick();const dialog=page.locator('#securityDetailDialog');await expect(dialog).toHaveAttribute('role','dialog');await expect(dialog).toHaveAttribute('aria-modal','true');await expect(dialog).toHaveAttribute('aria-labelledby','securityDetailTitle');await expect(dialog.locator('[role="tablist"]')).toHaveCount(1);const duplicates=await page.evaluate(()=>{const visible=element=>Boolean(element.offsetWidth||element.offsetHeight||element.getClientRects().length);const counts=new Map();document.querySelectorAll('[id]').forEach(element=>{if(visible(element))counts.set(element.id,(counts.get(element.id)??0)+1)});return[...counts.entries()].filter(([,count])=>count>1)});expect(duplicates).toEqual([]);const close=dialog.getByRole('button',{name:'銘柄詳細を閉じる'});const box=await close.boundingBox();expect(box.height).toBeGreaterThanOrEqual(44)});
