import { DEFAULT_FUNDAMENTAL_CONFIG, FUNDAMENTAL_PRESETS, applyFundamentalPreset, fundamentalRecords, screenFundamentals } from './fundamental-tuning-core.js';

const KEY='valuescope-fundamental-tuning-v1';
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const fmt=(value,digits=1)=>Number.isFinite(Number(value))?Number(value).toFixed(digits):'–';
let config=structuredClone(DEFAULT_FUNDAMENTAL_CONFIG);let records=[];
function range(label,id,min,max,step=1){return`<label class="ft-field"><span>${label}<b data-ft-value="${id}"></b></span><input id="${id}" type="range" min="${min}" max="${max}" step="${step}"></label>`}
function inject(){const host=$('#screeningLab .sl-controls');if(!host||$('#fundamentalTuning'))return;const panel=document.createElement('details');panel.id='fundamentalTuning';panel.className='ft-panel';panel.open=true;panel.innerHTML=`<summary>ファンダメンタル詳細設定</summary><div class="ft-body"><div class="ft-presets">${Object.entries(FUNDAMENTAL_PRESETS).map(([key,item])=>`<button type="button" data-ft-preset="${key}">${esc(item.label)}</button>`).join('')}</div><div class="ft-grid">${range('最低 割安スコア','ftValue',0,100)}${range('最低 品質スコア','ftQuality',0,100)}${range('最低 成長スコア','ftGrowth',0,100)}${range('最大 Trap Risk','ftTrap',0,100)}${range('最低 充足率','ftCompleteness',0,100)}${range('最低 利益利回り %','ftEarnings',-10,20,.5)}${range('最低 純資産/時価 %','ftBook',-20,150,1)}${range('最低 FCF利回り %','ftFcf',-20,30,.5)}${range('最低 ROE %','ftRoe',-30,50,.5)}${range('最低 営業利益率 %','ftMargin',-30,50,.5)}${range('最大 開示経過日','ftDisclosure',30,999,1)}</div><label class="ft-select"><span>欠損処理</span><select id="ftMissing"><option value="allow">許容</option><option value="neutral">中立50点</option><option value="exclude">除外</option></select></label><h4>Fundamental再計算ウェイト</h4><div class="ft-grid">${range('割安','ftWeightValue',0,60)}${range('品質','ftWeightQuality',0,60)}${range('成長','ftWeightGrowth',0,60)}${range('Trap安全性','ftWeightTrap',0,60)}${range('データ充足率','ftWeightCompleteness',0,60)}</div><div class="ft-summary"><span>通過 <b id="ftIncluded">0</b></span><span>除外 <b id="ftExcluded">0</b></span><span>設定 <b id="ftPreset">–</b></span></div><div id="ftPreview" class="ft-preview"></div></div>`;host.prepend(panel);bind();}
function map(){const pairs={ftValue:'minValueScore',ftQuality:'minQualityScore',ftGrowth:'minGrowthScore',ftTrap:'maxTrapRisk',ftCompleteness:'minCompleteness',ftEarnings:'minEarningsYieldPct',ftBook:'minBookToMarketPct',ftFcf:'minFcfYieldPct',ftRoe:'minRoePct',ftMargin:'minOperatingMarginPct',ftDisclosure:'maxDisclosureAgeDays'};for(const[id,key]of Object.entries(pairs))$(`#${id}`).value=String(config[key]);$('#ftMissing').value=config.missingPolicy;const weights={ftWeightValue:'value',ftWeightQuality:'quality',ftWeightGrowth:'growth',ftWeightTrap:'trapSafety',ftWeightCompleteness:'completeness'};for(const[id,key]of Object.entries(weights))$(`#${id}`).value=String(config.weights[key]);document.querySelectorAll('[data-ft-value]').forEach(node=>{node.textContent=$(`#${node.dataset.ftValue}`)?.value??''})}
function read(){const n=id=>Number($(`#${id}`).value);config={...config,minValueScore:n('ftValue'),minQualityScore:n('ftQuality'),minGrowthScore:n('ftGrowth'),maxTrapRisk:n('ftTrap'),minCompleteness:n('ftCompleteness'),minEarningsYieldPct:n('ftEarnings'),minBookToMarketPct:n('ftBook'),minFcfYieldPct:n('ftFcf'),minRoePct:n('ftRoe'),minOperatingMarginPct:n('ftMargin'),maxDisclosureAgeDays:n('ftDisclosure'),missingPolicy:$('#ftMissing').value,weights:{value:n('ftWeightValue'),quality:n('ftWeightQuality'),growth:n('ftWeightGrowth'),trapSafety:n('ftWeightTrap'),completeness:n('ftWeightCompleteness')}}}
function render(){const result=screenFundamentals(records,config);$('#ftIncluded').textContent=result.included.length;$('#ftExcluded').textContent=result.excluded.length;$('#ftPreset').textContent=FUNDAMENTAL_PRESETS[config.preset]?.label??'カスタム';$('#ftPreview').innerHTML=result.included.slice(0,5).map(row=>`<article><header><strong>${esc(row.company_name)}</strong><b>${fmt(row.user_fundamental_score)}</b></header><p>${esc(row.code)} · Value ${fmt(row.value_score)} / Quality ${fmt(row.quality_score)} / Growth ${fmt(row.growth_score)} / Trap ${fmt(row.trap_risk)}</p><small>利益利回り ${fmt(row.earnings_yield_pct,2)}% · FCF ${fmt(row.fcf_yield_pct,2)}% · ROE ${fmt(row.roe_pct,2)}% · 営業利益率 ${fmt(row.operating_margin_pct,2)}%</small></article>`).join('')||'<p>現在のFundamental条件を通過する銘柄はありません。</p>';localStorage.setItem(KEY,JSON.stringify(config));map()}
function bind(){$('#fundamentalTuning').addEventListener('input',event=>{if(event.target.matches('input,select')){config.preset='custom';read();render()}});document.querySelectorAll('[data-ft-preset]').forEach(button=>button.addEventListener('click',()=>{config=applyFundamentalPreset(button.dataset.ftPreset,config);map();render()}))}
async function start(){inject();try{config={...structuredClone(DEFAULT_FUNDAMENTAL_CONFIG),...(JSON.parse(localStorage.getItem(KEY)||'null')??{})};const response=await fetch(`./data/paper-trading/latest-report.json?ts=${Date.now()}`,{cache:'no-store'});const report=response.ok?await response.json():{};records=fundamentalRecords(report);map();render()}catch(error){const preview=$('#ftPreview');if(preview)preview.textContent=`Fundamental設定を読み込めません: ${error.message}`}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
